# grafana-httproute.yaml — ccmall 테스트 전용, 나중에 실제 저장소엔 도메인 바꿔서 반영
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-ccmall-test
  namespace: monitoring
spec:
  hostnames:
    - "grafana.ccmall.shop"
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: moongcheap-gateway
      namespace: infra
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: kube-prometheus-stack-grafana
          port: 80
          weight: 1